name = "Serendip"
uuid = "55555555-d952-479e-b559-988e8a4dc269"
version = "0.1.0"
authors = ["Raul Durand and others"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Arpack = "^0.5.0"
Cairo = "^1.1.0"
CodecZlib = "^0.7.0"
DataStructures = "^0.19.0"
DelimitedFiles = "^1.9.0"
Fontconfig_jll = "2.17.1"
FreeTypeAbstraction = "^0.10.0"
Glob = "^1.3.0"
Gmsh = "^0.3.0"
JSON = "^1.2.0"
SparseArrays = "^1.10.0"
StaticArrays = "^1.9.0"
StatsBase = "^0.34.0"
TranscodingStreams = "^0.11.0"
julia = "^1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
